=== AndyDelRisco/jberger.org/xml/articleindex.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="index">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="section">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="article">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="title" type="xs:string" />
                    <xs:element name="identifier" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AndyDelRisco/jberger.org/xml/articleindex.xml
<?xml version="1.0" encoding="utf-8"?>
<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="articleindex.xsd">
	<section name="Première section">
		<article>
			<title>Premier titre</title>
			<identifier>premier</identifier>
        </article>
		<article>
			<title>Un Deuxième Titre Beaucoup Plus Long que le Premier</title>
			<identifier>deuxieme</identifier>
        </article>
		<article>
			<title>Le troisième titre pour une super longue liste de titre : on veut que celui-ci soit extrêmement long</title>
			<identifier>troisieme</identifier>
        </article>
    </section>
	<section name="Encore une section">
		<article>
			<title>Un seul article dans cette section</title>
			<identifier>quatrieme</identifier>
        </article>
    </section>
	<section name="Dernière section">
		<article>
			<title>Dernier article</title>
			<identifier>cinquieme</identifier>
		</article>
    </section>
</index>
